#!/usr/bin/env python

Import("env")

thirdparty_dir = "#thirdparty/glad/"
env.Prepend(CPPPATH=[thirdparty_dir + "/glad/"])
env.Prepend(CPPPATH=[thirdparty_dir])
# SBC platform sources with updated file list
sbc_sources = [
    "os_sbc.cpp",
    "display_server_sdl.cpp",
    "audio_driver_sbc.cpp",
    "rendering_context_driver_vulkan_sdl.cpp",
    ]

# Add the SBC platform sources to the environment
prog = env.add_program("#bin/godot",["godot_sbc.cpp"] + sbc_sources)
